use_frameworks!

platform :ios, '12.0'

target 'SPVideo_Example' do
  pod 'SPVideo', :path => '../'

  target 'SPVideo_Tests' do
    inherit! :search_paths
  end
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
    end
  end
end
